# Generated by Django 5.2.1 on 2025-05-23 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedgraph_delete_savedchart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('shape', models.CharField(max_length=20)),
                ('eps_m', models.CharField(max_length=50)),
                ('eps_i', models.CharField(max_length=50)),
                ('f_range', models.CharField(max_length=50)),
                ('s_param', models.CharField(blank=True, max_length=20, null=True)),
                ('t_param', models.CharField(blank=True, max_length=20, null=True)),
                ('phi_c_param', models.CharField(blank=True, max_length=20, null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedGraph',
        ),
    ]
